package com.cy_siao.dao;

import com.cy_siao.model.Bed;
import com.cy_siao.util.DatabaseUtil;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class BedDao {
    private final DatabaseUtil databaseUtil;

    /**
     * The default constructor
     */
    public BedDao() {
        this.databaseUtil = new DatabaseUtil();
    }

    /**
     * Inserts a new Bed record into the database and assigns the generated ID to the provided Bed object.
     *
     * @param bed The Bed object to be created. The nbPlacesMax is determined by whether the bed is double (2) or single (1),
     *            and the IdRoom is taken from the bed to associate it with the correct room.
     *            The ID generated by the database will be assigned to the bed.
     *            Throws a RuntimeException if the database operation fails.
     */
    public void create(Bed bed) {
    String sql = "INSERT INTO Bed (nbPlacesMax, IdRoom) VALUES (?, ?)";
    try (Connection conn = databaseUtil.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
        
        pstmt.setInt(1, bed.isItDouble() ? 2 : 1);
        pstmt.setInt(2, bed.getIdRoom());
        pstmt.executeUpdate();

        try (ResultSet generatedKeys = pstmt.getGeneratedKeys()) {
            if (generatedKeys.next()) {
                bed.setId(generatedKeys.getInt(1));
            } else {
                throw new SQLException("Creating bed failed, no ID obtained.");
            }
        }
    } catch (SQLException e) {
        // Log l'erreur et/ou notifier l'utilisateur
        System.err.println("Erreur lors de la création du lit: " + e.getMessage());
        // Optionnel : relancer une RuntimeException pour interrompre le flux
        throw new RuntimeException("Erreur de base de données", e);
    }
}

    /**
     * Retrieves a Bed object from the database based on the provided ID.
     *
     * @param id The unique identifier of the bed to retrieve.
     * @return The Bed object corresponding to the given ID, or null if no bed with the specified ID exists
     *         or an error occurs during retrieval.
     */
    public Bed findById(int id) {
        String sql = "SELECT * FROM Bed WHERE Id = ?";
        try (Connection conn = databaseUtil.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setInt(1, id);
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    return extractBedFromResultSet(rs);
                }
            }
        } catch (SQLException e) {
            System.err.println("Error in finding bed by id: " + e.getMessage());
        }
        return null;
    }

    public List<Bed> findAll() {
        List<Bed> beds = new ArrayList<>();
        String sql = "SELECT * FROM Bed";
        try (Connection conn = databaseUtil.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {
            while (rs.next()) {
                beds.add(extractBedFromResultSet(rs));
            }
        } catch (SQLException e) {
            System.err.println("Error in finding all beds: " + e.getMessage());
        }
        return beds;
    }

    /**
     * The number of beds in the agency
     * @return the number of bed
     */
    public int countTotalBeds() {
        int count = 0;
        String sql = "SELECT COUNT(*) FROM Bed";
        try (Connection conn = databaseUtil.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {
            if (rs.next()) {
                count = rs.getInt(1);
            }
        } catch (SQLException e) {
            System.err.println("Error in counting all beds: " + e.getMessage());
        }
        return count;
    }

    /**
     * Updates an existing bed record in the database with the provided attributes.
     * The number of maximum places (nbPlacesMax) is derived from the bed's type (double or single),
     * and the room ID is updated based on the data in the given Bed object.
     *
     * @param bed The Bed object containing the updated information. This includes:
     *            - whether the bed is double or single (determines nbPlacesMax),
     *            - the ID of the associated room (IdRoom),
     *            - and the unique ID of the bed (Id) to locate the record in the database.
     */
    public void update(Bed bed) {
        String sql = "UPDATE Bed SET nbPlacesMax = ?, IdRoom = ? WHERE Id = ?";
        try (Connection conn = databaseUtil.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setInt(1, bed.isItDouble() ? 2 : 1);
            pstmt.setInt(2, bed.getIdRoom());
            pstmt.setInt(3, bed.getId());
            pstmt.executeUpdate();
        } catch (SQLException e) {
            System.err.println("Error in updating bed: " + e.getMessage());
        }
    }


    public void delete(int id) {
        String sql = "DELETE FROM Bed WHERE Id = ?";
        try (Connection conn = databaseUtil.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setInt(1, id);
            pstmt.executeUpdate();
        } catch (SQLException e) {
            System.err.println("Error in deleting bed: " + e.getMessage());
        }
    }

    private Bed extractBedFromResultSet(ResultSet rs) throws SQLException {
        Bed bed = new Bed();
        bed.setId(rs.getInt("Id"));
        bed.setIdRoom(rs.getInt("IdRoom"));
        if (rs.getInt("nbPlacesMax") == 2) {
            bed.isDouble();
        }
        return bed;
    }
}